[env:genericSTM32F103RE]
platform = ststm32
board = genericSTM32F103RE
framework = arduino
upload_protocol = stlink

; Vajalikud teegid
lib_deps = 
    paulstoffregen/OneWire@^2.3.7
    milesburton/DallasTemperature@^3.9.0
    olikraus/U8g2@^2.32.15